services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env

    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../solar-load-calculator/Dockerfile.frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solar_load
    volumes:
      - solar_load_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  solar_load_pgdata:

